language: java
jdk:
  - oraclejdk8
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; mvn deploy --settings deploy/settings.xml -DperformRelease=true -DskipTests=true; fi
