language: java
jdk:
  - oraclejdk8
after_success:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - echo "$TRAVIS_BRANCH" = "master"
  - echo "$TRAVIS_PULL_REQUEST" = "false"
  - echo ["$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; mvn deploy --settings deploy/settings.xml -DperformRelease=true -DskipTests=true; fi
env:
  global:
    - secure: "uT4ikl0UXRhP7Z2/FwpflCG68zTd01WagWC7NWoAYufCdL1ppxeJovqCmBAD6BB3v+3LpUSk6V4LUdUKvI+ih86dv7jU44W17EKTZYkQEVgytF4Smt/jaW6TQrjC7iqmQNwKqpw+NFZlDc5LrwZ2Ngrh9OCZwRMLINrI2LuPLehddnymy9Yjq8KUyHwbAjiqIHPZkdfL5Di9D4cL723Ll9lgs0VB3JdWNGTS+TxINtd4ZEkvMCVABFxSwnCGn+A9uTXBGbocm5vbccdI4p+e7M8pbO/aDmOU3a0QohupBeea9OjSFsKGvh3Zx0XQakcmA0Ou1pKPtckZkhHhjaBFSBr/dJvRco0ZesHgS5cVcmuBYwQBTlP7clwmrly4/9rRL20iy0e+oFNTuVamOfWrct83y5nJb57Ok9WtkuEH2MLCMJKX3IVeujKU0UMcT0gdMeOgZ9LK36t9/BNFH3+jiGbBFCxbuWbhNUGpACaQnLg7aK5oQmYU8ynk7uZ1vMic2giWvuwacGyb4zD/MXCpor+aPz0rXuWMp0anVgu63p37naj5evBSp4iM4T45Le8YOG6HNul1LI82LcfjqM+2mL3qH68sniPnzmJCc="
    - secure: "B4k61SpbItvchAIlTP7NCCQIL0GXtopSSKbNlMmLjeVAug3Hn4iEgO9ExYkgUDBV2X3arUtJCwwaAWMrwhk9VF+o+hVGmdiNU7kSYBcLanMHv5cdmMA/1evkIo51irPGfIca/E/Z6FFtagyu+kOgaNmBufGoeZoR90Hf4jtU1qpFY3WxLjRt7Kb1pxGmwwB8R28amn/O38gMrijcRpr8Mn+LznPxHbioHdjBDSup+0v86O/96LGCLjoqI+9H1bug81awwRzYhrziBWiFFulTeKGcOhir3dMxT64G/6SUkSqvjZ48zBqvfC0oqNvTWsu+qowIpnWn+hDUltM+rg3C6l+cHdMpl0GQ3X7QQ7fJYN8wAqDItFFGBceBkihPt6NNZFYgd+l/80uoznb9F65WAQNm4S0XBDMfOCaBN0/3spb41ccju0j/BVZ6Xs+PNYfSlncOAbkXZZ7OzqZk9Se/UtGJXJrw5RrO90hm/HjjdlZ4uVMNLPF0bKrwp/XijK/7eP+knJzNYBbdq7ceaUFI7KDFocvK1m32sjKeywzArL29XRiiZrNpkVY83WCWrmSh6JTdCSDx2QtG29TQg7hiiH4hd9VDC2p6PFpLC1Gyw6jZrfpvDLBHNcSIH1nG7lzM+DfeLrHeiqj8fAVIg9HlFmDfZiaajmYraPtZkr8LqoA="
